export {
  analyzeProject,
  DEFAULT_EXCLUDED_DIRECTORIES,
  type AnalysisTotals,
  type AnalyzeProjectOptions,
  type Diagnostic,
  type DiagnosticSeverity,
  type ExportKind,
  type ExportSymbol,
  type FileAnalysis,
  type ImportKind,
  type ImportSymbol,
  type ProjectAnalysis,
  type ReexportSymbol,
  type UnusedExport,
} from "./analyzer";

export {
  analyzeCodeHealth,
  analyzeCodeHealthSource,
  codeHealthIssueLabel,
  type AnalyzeCodeHealthOptions,
  type CodeHealthAnalysis,
  type CodeHealthDiagnostic,
  type CodeHealthFileAnalysis,
  type CodeHealthIssue,
  type CodeHealthIssueType,
  type CodeHealthProgress,
  type CodeHealthSeverity,
  type CodeHealthTotals,
} from "./code-health";

export {
  parseCliArgs,
  usage,
  VERSION,
  type CliOptions,
  type OutputMode,
} from "./cli";

export {
  analyzeMemoryMeasurements,
  DEFAULT_MEMORY_WINDOW_SIZE,
  forceGarbageCollection,
  MemoryMonitor,
  MIN_MEMORY_DURATION_MS,
  MIN_MEMORY_SAMPLES,
  type AnalyzeMemoryOptions,
  type MemoryAnalysis,
  type MemoryConfidence,
  type MemoryMeasurement,
  type MemoryMetric,
  type MemoryMetricTrend,
  type MemoryMonitorOptions,
  type MemorySampler,
  type MemoryVerdict,
} from "./memory";

export {
  adjustAlacrittyValue,
  alacrittyConfigWarnings,
  alacrittySetting,
  buildAlacrittyConfig,
  defaultAlacrittyConfigPath,
  ALACRITTY_MANAGED_END,
  ALACRITTY_MANAGED_START,
  ALACRITTY_SETTINGS,
  findAlacrittyConfigIssues,
  loadAlacrittyConfig,
  parseAlacrittyConfig,
  saveAlacrittyConfig,
  validateAlacrittyValue,
  type AlacrittyConfigIssue,
  type AlacrittyConfigSaveResult,
  type AlacrittyConfigSnapshot,
  type AlacrittyLiteralKind,
  type AlacrittySettingDefinition,
  type AlacrittySettingGroup,
  type AlacrittySettingKind,
} from "./alacritty-config";

export {
  adjustKittyValue,
  buildKittyConfig,
  defaultKittyConfigPath,
  findKittyConfigIssues,
  KITTY_MANAGED_END,
  KITTY_MANAGED_START,
  KITTY_SETTINGS,
  kittyConfigWarnings,
  kittySetting,
  loadKittyConfig,
  parseKittyConfig,
  parseKittyDirectives,
  saveKittyConfig,
  validateKittyValue,
  type KittyConfigSaveResult,
  type KittyConfigIssue,
  type KittyConfigSnapshot,
  type KittySettingDefinition,
  type KittySettingGroup,
  type KittySettingKind,
} from "./kitty-config";

export {
  adjustHerdrValue,
  buildHerdrConfig,
  defaultHerdrConfigPath,
  findHerdrConfigIssues,
  HERDR_SETTINGS,
  herdrConfigWarnings,
  herdrSetting,
  loadHerdrConfig,
  parseHerdrConfig,
  saveHerdrConfig,
  validateHerdrValue,
  type HerdrConfigIssue,
  type HerdrConfigSaveResult,
  type HerdrConfigSnapshot,
  type HerdrLiteralKind,
  type HerdrSettingDefinition,
  type HerdrSettingGroup,
  type HerdrSettingKind,
} from "./herdr-config";
